using System;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.InteropServices;
using ThreeDEngine.Core.Particles;
using ThreeDEngine.Core.Rendering.Rhi;
using ThreeDEngine.Core.Scene;

namespace ThreeDEngine.Core.Rendering.GpuDriven;

internal readonly record struct GpuParticleFrame3D(
    RhiResourceHandle3D Emitters,
    RhiResourceHandle3D SourceStates,
    RhiResourceHandle3D DestinationStates,
    RhiResourceHandle3D Counters,
    RhiResourceHandle3D IndirectCommands,
    int EmitterCount,
    int ParticleCapacity,
    int UploadedBytes,
    int WorkgroupCount);

/// <summary>
/// Persistent GPU particle state. CPU particle data is accepted only as an explicit initialization
/// payload after a system/configuration mutation. Frame integration, lifetime tests, emission,
/// compaction and indirect instance counts are generated by the compute pipeline.
/// </summary>
internal sealed class GpuParticlePipeline3D : IDisposable
{
    private const int DrawIndirectStride = 16;
    private readonly List<ParticleSystem3D> _systems = new(32);
    private readonly List<GpuParticleEmitterRecord3D> _emitters = new(32);
    private readonly Dictionary<string, ParticleAllocation> _allocations = new(StringComparer.Ordinal);
    private readonly string _owner = "gpu-driven-particles";
    private RhiDevice3D? _device;
    private uint _deviceGeneration;
    private RhiResourceHandle3D _emittersBuffer;
    private RhiResourceHandle3D _statesA;
    private RhiResourceHandle3D _statesB;
    private RhiResourceHandle3D _counters;
    private RhiResourceHandle3D _indirectCommands;
    private int _emittersCapacity;
    private int _statesACapacity;
    private int _statesBCapacity;
    private int _countersCapacity;
    private int _indirectCapacity;
    private int _layoutVersion;
    private string _layoutSignature = string.Empty;
    private bool _sourceIsA = true;
    private bool _disposed;

    public GpuParticleFrame3D Prepare(
        SceneRenderPlan3D plan,
        RhiDevice3D device,
        RhiCommandEncoder3D encoder,
        GpuDrivenRenderSettings3D settings)
    {
        ArgumentNullException.ThrowIfNull(plan);
        ArgumentNullException.ThrowIfNull(device);
        ArgumentNullException.ThrowIfNull(encoder);
        ArgumentNullException.ThrowIfNull(settings);
        ObjectDisposedException.ThrowIf(_disposed, this);
        device.Capabilities.RequireProfile(RhiCapabilityProfile3D.GpuDriven, "GPU particle preparation");
        ResetForDevice(device);
        CollectSystems(plan);

        if (_systems.Count == 0)
            return default;
        if (!settings.EnableGpuParticles)
            throw new InvalidOperationException("The scene contains particle systems but GPU particles are disabled. CPU particle rendering fallback is not permitted.");
        if (plan.Frame.Scene.UpdateLoop.AdvanceParticles)
            throw new InvalidOperationException("GPU-driven particles require Scene.UpdateLoop.AdvanceParticles=false. Running CPU and GPU particle simulation concurrently is not permitted.");

        var totalCapacity = 0;
        for (var i = 0; i < _systems.Count; i++)
            totalCapacity = checked(totalCapacity + _systems[i].Settings.Capacity);
        if (totalCapacity > settings.MaximumParticles)
            throw new InvalidOperationException($"GPU particle capacity {totalCapacity} exceeds configured MaximumParticles={settings.MaximumParticles}. Particles were not dropped and no CPU fallback was selected.");

        var signature = BuildLayoutSignature();
        var layoutChanged = !string.Equals(signature, _layoutSignature, StringComparison.Ordinal);
        if (layoutChanged)
        {
            _layoutSignature = signature;
            _layoutVersion = checked(_layoutVersion + 1);
            RebuildAllocations();
        }

        EnsureBuffer(device, ref _emittersBuffer, ref _emittersCapacity, "emitters",
            BytesFor<GpuParticleEmitterRecord3D>(global::System.Math.Max(1, _systems.Count)),
            RhiBufferUsage3D.Storage | RhiBufferUsage3D.CopyDestination);
        EnsureBuffer(device, ref _statesA, ref _statesACapacity, "states-a",
            BytesFor<GpuParticleStateRecord3D>(global::System.Math.Max(1, totalCapacity)),
            RhiBufferUsage3D.Storage | RhiBufferUsage3D.CopyDestination);
        EnsureBuffer(device, ref _statesB, ref _statesBCapacity, "states-b",
            BytesFor<GpuParticleStateRecord3D>(global::System.Math.Max(1, totalCapacity)),
            RhiBufferUsage3D.Storage | RhiBufferUsage3D.CopyDestination);
        EnsureBuffer(device, ref _counters, ref _countersCapacity, "counters",
            checked((long)global::System.Math.Max(1, _systems.Count) * sizeof(uint)),
            RhiBufferUsage3D.Storage | RhiBufferUsage3D.CopyDestination);
        EnsureBuffer(device, ref _indirectCommands, ref _indirectCapacity, "indirect",
            checked((long)global::System.Math.Max(1, _systems.Count) * DrawIndirectStride),
            RhiBufferUsage3D.Storage | RhiBufferUsage3D.Indirect | RhiBufferUsage3D.CopyDestination);

        var ring = device.CurrentUploadRing ?? throw new InvalidOperationException("GPU particle upload requires an open RHI frame.");
        _emitters.Clear();
        var uploadedBytes = 0;
        for (var i = 0; i < _systems.Count; i++)
        {
            var system = _systems[i];
            var allocation = _allocations[system.Id];
            _emitters.Add(BuildEmitter(system, allocation, i));
            if (layoutChanged || allocation.UploadedParticleVersion != system.ParticleVersion)
            {
                uploadedBytes += UploadInitialState(system, allocation, encoder, ring, _statesA);
                uploadedBytes += UploadInitialState(system, allocation, encoder, ring, _statesB);
                allocation.UploadedParticleVersion = system.ParticleVersion;
                _allocations[system.Id] = allocation;
            }
        }

        uploadedBytes += UploadList(encoder, ring, _emittersBuffer, _emitters);
        encoder.ClearBuffer(_counters, 0, checked((long)global::System.Math.Max(1, _systems.Count) * sizeof(uint)));
        encoder.ClearBuffer(_indirectCommands, 0, checked((long)global::System.Math.Max(1, _systems.Count) * DrawIndirectStride));

        var source = _sourceIsA ? _statesA : _statesB;
        var destination = _sourceIsA ? _statesB : _statesA;
        var workgroups = DivideRoundUp(totalCapacity, settings.ParticleWorkgroupSize);
        return new GpuParticleFrame3D(
            _emittersBuffer,
            source,
            destination,
            _counters,
            _indirectCommands,
            _systems.Count,
            totalCapacity,
            uploadedBytes,
            workgroups);
    }

    public void CompleteFrame()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        _sourceIsA = !_sourceIsA;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        if (_device is not null && !_device.IsDisposed)
        {
            Release(_emittersBuffer);
            Release(_statesA);
            Release(_statesB);
            Release(_counters);
            Release(_indirectCommands);
        }
        _allocations.Clear();
        _systems.Clear();
        _emitters.Clear();
        _device = null;
    }

    private void CollectSystems(SceneRenderPlan3D plan)
    {
        _systems.Clear();
        var renderables = plan.Frame.Snapshot.RenderablesInternal;
        for (var i = 0; i < renderables.Length; i++)
        {
            if (renderables[i] is ParticleSystem3D particles && particles.IsVisible)
                _systems.Add(particles);
        }
        _systems.Sort(static (left, right) => string.CompareOrdinal(left.Id, right.Id));
    }

    private string BuildLayoutSignature()
    {
        var builder = new global::System.Text.StringBuilder(_systems.Count * 48);
        for (var i = 0; i < _systems.Count; i++)
            builder.Append(_systems[i].Id).Append(':').Append(_systems[i].Settings.Capacity).Append(';');
        return builder.ToString();
    }

    private void RebuildAllocations()
    {
        _allocations.Clear();
        var offset = 0;
        for (var i = 0; i < _systems.Count; i++)
        {
            var system = _systems[i];
            _allocations.Add(system.Id, new ParticleAllocation(offset, system.Settings.Capacity, long.MinValue));
            offset = checked(offset + system.Settings.Capacity);
        }
    }

    private GpuParticleEmitterRecord3D BuildEmitter(ParticleSystem3D system, ParticleAllocation allocation, int index)
    {
        var settings = system.Settings;
        var emitter = system.Emitter;
        var flags = 0u;
        if (system.IsPlaying) flags |= 1u;
        if (settings.Looping) flags |= 1u << 1;
        if (settings.SimulationSpace == ParticleSimulationSpace3D.World) flags |= 1u << 2;
        if (settings.RenderMode == ParticleRenderMode3D.CameraFacingQuad) flags |= 1u << 3;
        return new GpuParticleEmitterRecord3D
        {
            Model = system.GetModelMatrix(),
            DirectionEmissionRate = new Vector4(emitter.Direction, settings.EmissionRatePerSecond),
            GravityLifetime = new Vector4(emitter.Gravity, settings.ParticleLifetimeSeconds),
            SizeSpeedSpread = new Vector4(settings.StartSize, settings.EndSize, settings.InitialSpeed, settings.Spread),
            StartColor = new Vector4(settings.StartColor.R, settings.StartColor.G, settings.StartColor.B, settings.StartColor.A),
            EndColor = new Vector4(settings.EndColor.R, settings.EndColor.G, settings.EndColor.B, settings.EndColor.A),
            StateOffset = checked((uint)allocation.Offset),
            Capacity = checked((uint)allocation.Capacity),
            Flags = flags,
            RandomSeed = StableHash(system.Id) ^ checked((uint)(_layoutVersion * 16777619)) ^ checked((uint)index)
        };
    }

    private static int UploadInitialState(
        ParticleSystem3D system,
        ParticleAllocation allocation,
        RhiCommandEncoder3D encoder,
        RhiUploadRing3D ring,
        RhiResourceHandle3D destination)
    {
        var stride = Marshal.SizeOf<GpuParticleStateRecord3D>();
        var byteOffset = checked((long)allocation.Offset * stride);
        var byteCapacity = checked((long)allocation.Capacity * stride);
        encoder.ClearBuffer(destination, byteOffset, byteCapacity);
        var count = global::System.Math.Min(system.AliveCount, allocation.Capacity);
        if (count == 0) return 0;
        var bytes = checked(count * stride);
        var memory = ring.Allocate(bytes, 16);
        var records = MemoryMarshal.Cast<byte, GpuParticleStateRecord3D>(memory.Memory.Span);
        var particles = system.Particles;
        for (var i = 0; i < count; i++)
        {
            var particle = particles[i];
            records[i] = new GpuParticleStateRecord3D
            {
                PositionAge = new Vector4(particle.Position, particle.Age),
                VelocityLifetime = new Vector4(particle.Velocity, particle.Lifetime),
                Color = new Vector4(particle.StartColor.R, particle.StartColor.G, particle.StartColor.B, particle.StartColor.A),
                SizeRotationFlags = new Vector4(particle.StartSize, particle.EndSize, 0f, particle.Alive ? 1f : 0f)
            };
        }
        encoder.WriteBuffer(destination, byteOffset, memory.Memory);
        return bytes;
    }

    private static int UploadList<T>(RhiCommandEncoder3D encoder, RhiUploadRing3D ring, RhiResourceHandle3D destination, List<T> values)
        where T : struct
    {
        if (values.Count == 0) return 0;
        var bytes = checked(Marshal.SizeOf<T>() * values.Count);
        var memory = ring.Allocate(bytes, 16);
        var span = MemoryMarshal.Cast<byte, T>(memory.Memory.Span);
        global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(values).CopyTo(span);
        encoder.WriteBuffer(destination, 0, memory.Memory);
        return bytes;
    }

    private void ResetForDevice(RhiDevice3D device)
    {
        var generation = device.Resources.ContextGeneration;
        if (ReferenceEquals(_device, device) && _deviceGeneration == generation) return;
        if (_device is not null && !_device.IsDisposed && _deviceGeneration == _device.Resources.ContextGeneration)
        {
            Release(_emittersBuffer);
            Release(_statesA);
            Release(_statesB);
            Release(_counters);
            Release(_indirectCommands);
        }
        _device = device;
        _deviceGeneration = generation;
        _emittersBuffer = default;
        _statesA = default;
        _statesB = default;
        _counters = default;
        _indirectCommands = default;
        _emittersCapacity = 0;
        _statesACapacity = 0;
        _statesBCapacity = 0;
        _countersCapacity = 0;
        _indirectCapacity = 0;
        _layoutSignature = string.Empty;
        _allocations.Clear();
        _sourceIsA = true;
    }

    private void EnsureBuffer(
        RhiDevice3D device,
        ref RhiResourceHandle3D handle,
        ref int capacity,
        string name,
        long requiredBytes,
        RhiBufferUsage3D usage)
    {
        if (requiredBytes > int.MaxValue)
            throw new InvalidOperationException($"GPU particle buffer '{name}' requires {requiredBytes} bytes, exceeding the current managed descriptor capacity.");
        if (handle.IsValid && requiredBytes <= capacity) return;
        if (handle.IsValid) device.Resources.Release(handle);
        capacity = Grow(capacity, checked((int)requiredBytes));
        handle = device.CreateBuffer(
            $"{_owner}:{name}",
            new RhiBufferDescriptor3D(capacity, usage),
            capacity,
            _owner);
    }

    private void Release(RhiResourceHandle3D handle)
    {
        if (handle.IsValid) _device?.Resources.Release(handle);
    }

    private static int BytesFor<T>(int count) where T : struct
        => checked(Marshal.SizeOf<T>() * count);

    private static int Grow(int current, int required)
    {
        var next = global::System.Math.Max(256, current);
        while (next < required) next = checked(next * 2);
        return next;
    }

    private static int DivideRoundUp(int value, int divisor)
        => value == 0 ? 0 : checked((value + divisor - 1) / divisor);

    private static uint StableHash(string value)
    {
        var hash = 2166136261u;
        for (var i = 0; i < value.Length; i++)
        {
            hash ^= value[i];
            hash *= 16777619u;
        }
        return hash;
    }

    private struct ParticleAllocation
    {
        public ParticleAllocation(int offset, int capacity, long uploadedParticleVersion)
        {
            Offset = offset;
            Capacity = capacity;
            UploadedParticleVersion = uploadedParticleVersion;
        }

        public int Offset;
        public int Capacity;
        public long UploadedParticleVersion;
    }
}
