namespace ThreeDEngine.Core.Rendering;

public sealed class RenderStats
{
    public int ObjectCount { get; set; }
    public int RenderableCount { get; set; }
    public int PickableCount { get; set; }
    public int ColliderCount { get; set; }
    public int DynamicBodyCount { get; set; }
    public int StaticColliderCount { get; set; }
    public int VisibleMeshCount { get; set; }
    public int ControlPlaneCount { get; set; }
    public int TriangleCount { get; set; }
    public int DrawCallCount { get; set; }
    public int EstimatedDrawCallCount { get; set; }
    public int InstancedBatchCount { get; set; }
    public int HighScaleInstanceCount { get; set; }
public int ParticleSystemCount { get; set; }
public int ParticleCount { get; set; }
public int ParticleVertexCount { get; set; }
public long ParticleMeshUploadBytes { get; set; }
public int InstancedMeshLayerCount { get; set; }
public int InstancedMeshInstanceCount { get; set; }
public int ThroughputFallbackDrawCount { get; set; }
public int RetainedThroughputDrawCount { get; set; }
public bool IndirectDrawRequested { get; set; }
public bool IndirectDrawActive { get; set; }
public bool BindlessTextureRequested { get; set; }
public bool BindlessTextureActive { get; set; }
public int ImportedModelCount { get; set; }
public int SkinnedModelCount { get; set; }
public int AnimatedModelCount { get; set; }
public int SkinMatrixCount { get; set; }
public int SkinnedPrimitiveCount { get; set; }
public long SkinningVertexPayloadBytes { get; set; }
public bool GpuSkinningRequested { get; set; }
public bool GpuSkinningActive { get; set; }
public string SkinningFallbackReason { get; set; } = string.Empty;
    public int RenderPipelineMode { get; set; }
    public bool DeferredRequested { get; set; }
    public bool DeferredActive { get; set; }
    public bool GBufferActive { get; set; }
    public int GBufferTargetCount { get; set; }
    public bool SsaoRequested { get; set; }
    public bool SsaoActive { get; set; }
    public int SsaoSampleCount { get; set; }
    public double SsaoMilliseconds { get; set; }
    public bool HdrRequested { get; set; }
    public bool HdrActive { get; set; }
    public int ToneMappingMode { get; set; }
    public bool ToneMappingActive { get; set; }
    public float ToneMappingExposure { get; set; }
    public float ToneMappingGamma { get; set; }
    public int RenderPassCount { get; set; }
    public bool MotionVectorsRequested { get; set; }
    public bool MotionVectorsActive { get; set; }
    public string RenderPipelineReason { get; set; } = string.Empty;
    public int CulledObjectCount { get; set; }
    public int DirtyMeshUploads { get; set; }
    public int DirtyTextureUploads { get; set; }
    public int DirectionalLightCount { get; set; }
    public int PointLightCount { get; set; }
    public int SpotLightCount { get; set; }
    public int RenderGeometryCount { get; set; }
    public int VertexBufferUploadCount { get; set; }
    public int IndexBufferUploadCount { get; set; }
    public long VertexBufferUploadBytes { get; set; }
    public long IndexBufferUploadBytes { get; set; }
    public long MeshUploadBytes { get; set; }
    public int ShaderProgramSwitches { get; set; }
    public int TangentSpaceMeshCount { get; set; }
    public int GeneratedNormalMeshCount { get; set; }
    public int GeneratedTangentMeshCount { get; set; }
    public int NormalMappedMeshCount { get; set; }
    public int WireframeOverlayDrawCalls { get; set; }
    public int SilhouetteOverlayDrawCalls { get; set; }
    public long TangentUploadBytes { get; set; }
    public long WireframeIndexUploadBytes { get; set; }
    public long PacketBytes { get; set; }
    public long TextureUploadBytes { get; set; }
    public bool SkyboxEnabled { get; set; }
    public int SkyboxMode { get; set; }
    public int SkyboxDrawCalls { get; set; }
    public bool DirectionalShadowEnabled { get; set; }
    public int ShadowMapCount { get; set; }
    public int ShadowCasterCount { get; set; }
    public int ShadowMapResolution { get; set; }
    public string ShadowMapReason { get; set; } = string.Empty;
    public double ShadowMapMilliseconds { get; set; }
    public int RegistryVersion { get; set; }
    public int MeshCacheCount { get; set; }
    public int SceneTraversalCount { get; set; }
    public int TotalChunkCount { get; set; }
    public int VisibleChunkCount { get; set; }
    public int LodDetailedCount { get; set; }
    public int LodSimplifiedCount { get; set; }
    public int LodProxyCount { get; set; }
    public int LodBillboardCount { get; set; }
    public int LodCulledCount { get; set; }
    public int HighScaleVisiblePartInstanceCount { get; set; }
    public int InstanceBufferUploads { get; set; }
    public int RetainedTransformSlotUpdateCount { get; set; }
    public int InstanceBufferSubDataUploads { get; set; }
    public int StateBufferUploads { get; set; }
    public int StateBufferSubDataUploads { get; set; }
    public long InstanceUploadBytes { get; set; }
    public long TransformUploadBytes { get; set; }
    public long StateUploadBytes { get; set; }
    public double PacketBuildMilliseconds { get; set; }
    public double SerializationMilliseconds { get; set; }
    public double UploadMilliseconds { get; set; }
    public double BackendMilliseconds { get; set; }
    public double PickingMilliseconds { get; set; }
    public double PhysicsMilliseconds { get; set; }
    public double LiveSnapshotMilliseconds { get; set; }
    public double CpuPreparationMilliseconds { get; set; }
    public double HighScalePlanMilliseconds { get; set; }
    public double HighScaleBufferBuildMilliseconds { get; set; }
    public double HighScaleUploadMilliseconds { get; set; }
    public double SchedulerDelayMilliseconds { get; set; }
    public double FrameTotalMilliseconds { get; set; }
    public double RenderScheduleDelayMilliseconds { get; set; }
    public double AllocatedMegabytesPerSecond { get; set; }
    public long AllocatedBytesPerFrame { get; set; }
    public long ManagedHeapBytes { get; set; }
    public int Gen0Collections { get; set; }
    public int Gen1Collections { get; set; }
    public int Gen2Collections { get; set; }
    public double AdaptiveQualityScale { get; set; } = 1d;
    public bool FpsLocked { get; set; }
    public double TargetFps { get; set; }
    public bool ContinuousRendering { get; set; }
    public bool FrameInterpolationEnabled { get; set; }
    public bool AdaptivePerformanceEnabled { get; set; }
    public double InterpolationAlpha { get; set; }
    public long ManagedAllocatedBytes { get; set; }
    public int RenderTargetWidth { get; set; }
    public int RenderTargetHeight { get; set; }
    public int BakedHighScalePartDraws { get; set; }
    public bool WebGlClientHighScaleRuntime { get; set; }
    public bool WebGlClientGpuTransformAnimation { get; set; }
    public int WebGlVersion { get; set; }
    public double JsCullMilliseconds { get; set; }
    public double JsDrawMilliseconds { get; set; }
    public double JsFrameMilliseconds { get; set; }
    public double JsPatchMilliseconds { get; set; }
    public int JsDrawBatchCount { get; set; }
    public int JsTransformPatchRanges { get; set; }
    public int JsStatePatchRanges { get; set; }
    public long JsTransformPatchBytes { get; set; }
    public long JsStatePatchBytes { get; set; }
    public int JsAnimationUploadBatches { get; set; }
    public long JsAnimationUploadBytes { get; set; }
    public int JsTexturePayloadErrors { get; set; }
    public int JsPalettePayloadErrors { get; set; }
    public int WebGlStateChanges { get; set; }
    public int WebGlUniformUpdates { get; set; }
    public int WebGlTextureBinds { get; set; }
    public int WebGlBufferBinds { get; set; }
    public int WebGlVaoBinds { get; set; }

    public static RenderStats Empty => new RenderStats();
}
